#!/usr/bin/env bash

nohup python -u 0_TT_ft_hyper_main.py > test.txt &

# tcga pretrain     zero shot to    BRCA dataset
nohup python -u 0_TT_ft_hyper_main.py --num 0 > record/tcga_BRCA.txt &

# brca pretrain     zero shot to    BRCA dataset
nohup python -u 0_TT_ft_hyper_main.py --num 2 > record/brca_BRCA.txt &

["tcga", "blca", "brca", "cesc", "coad", "gbm", "hnsc", "kich", "kirc", 
"kirp", "lgg", "lihc", "luad", "lusc", "ov", "paad", "prad", "read", "sarc", "skcm", "stad", "ucec"][Num] #21

srun --gres=gpu:a100:1 --time 3-12:00:00 python -u 0_TT_ft_hyper_main.py --num 2 --select_gene_method HVG > ../record/brca_BRCA.txt &
